const ACTIONS ={
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    UPDATE_AVATAR:'UPDATE_AVATAR',

    GET_ERRORS : 'GET_ERRORS',
    CLEAR_ERRORS : 'CLEAR_ERRORS',

    LOAD_FACULTY: 'LOAD_FACULTY',
    ADD_FACULTY: 'ADD_FACULTY',
    REMOVE_FACULTY: 'REMOVE_FACULTY',
    CLEAR_FACULTY: 'CLEAR_FACULTY',

    LOAD_INCHARGE: 'LOAD_INCHARGE',

    LOAD_GATEPASS:'LOAD_GATEPASS',
    LOAD_SICKPASS:'LOAD_SICKPASS',
    LOAD_EVENTPASS:'LOAD_EVENTPASS',
    LOAD_OTHERPASS:'LOAD_OTHERPASS',
    LOAD_LEAVE:'LOAD_LEAVE',

    UPDATE_GATEPASS:'UPDATE_GATEPASS',
    UPDATE_SICKASS:'UPDATE_SICKASS',
    UPDATE_EVENTPASS:'UPDATE_EVENTPASS',
    UPDATE_OTHERPASS:'UPDATE_OTHERPASS',
    UPDATE_LEAVE:'UPDATE_LEAVE'
    




}

export default ACTIONS